services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    build: ./frontend
    container_name: nextjs
    depends_on:
      - backend
    ports:
      - $FRONTEND_PORT:3000
    volumes:
      - ./frontend:/app
      - ./frontend/.env.local:/app/.env.local
      - /app/node_modules
    env_file:
      - ./frontend/.env.local

  backend:
    build: ./backend
    container_name: springboot
    depends_on:
      - db
    ports:
      - $BACKEND_PORT:8080
    volumes:
      - ./backend:/app  # Mount backend source code for hot reload
      - m2-repo:/root/.m2  # Cache Maven dependencies
    working_dir: /app
    env_file:
      - ./backend/.env
    environment:
      - JAVA_TOOL_OPTIONS=-Dspring.devtools.restart.poll-interval=1000

volumes:
  db-data:
  m2-repo: